#!/usr/bin/env zsh

#sudo sh -c 'echo "%admin ALL=(ALL) NOPASSWD: /usr/local/bin/openconnect" > /etc/sudoers.d/foo'

#
# ZSH functions to start/stop OpenConnect VPN client
#
# In my setup the VPN username is the same as $USER
#

COLOR_MACROS_FILE=${ZDOTDIR}/color_macros
[ -f $COLOR_MACROS_FILE ] && source $COLOR_MACROS_FILE || { echo -e "${BLINK}${BIYellow}${COLOR_MACROS_FILE} is required.${Color_Off}"; return; }

function vpn-down() {
  if pgrep -x "openconnect" > /dev/null
  then
    echo "${BIRed}Killing the VPN ...${Color_Off}"
    sleep 1
    sudo kill -2 `pgrep openconnect` &> /dev/null
    echo "${REPLACE_LINE}${CHECK_MARK} VPN killed!${Color_Off}"
else
    echo "${EXCLAMATION_MARK}${BICyan}VPN is already not running!${Color_Off}"
    return
  fi
}

vpn-down "$@"
