#!/usr/bin/env bash

#sudo sh -c 'echo "%admin ALL=(ALL) NOPASSWD: /usr/local/bin/openconnect" > /etc/sudoers.d/foo'

#
# ZSH functions to start/stop OpenConnect VPN client
#
# In my setup the VPN username is the same as $USER
#
export VPN_CONFIG_PATH=${XDG_CONFIG_HOME}/tfxcorp/
export VPN_HOST=$(< ${VPN_CONFIG_PATH}/vpnh)
export VPN_GROUP=$(< ${VPN_CONFIG_PATH}/vpng)

COLOR_MACROS_FILE=${ZDOTDIR}/color_macros
[ -f $COLOR_MACROS_FILE ] && source $COLOR_MACROS_FILE || { echo -e "${BLINK}${BIYellow}${COLOR_MACROS_FILE} is required.${Color_Off}"; return; }
