#!/usr/bin/env zsh

#sudo sh -c 'echo "%admin ALL=(ALL) NOPASSWD: /usr/local/bin/openconnect" > /etc/sudoers.d/foo'

#
# ZSH functions to start/stop OpenConnect VPN client
#
# In my setup the VPN username is the same as $USER
#

source vpn-init

function vpn-up() {
  
  op signin --account E44VP6N4VRGWZKIFB3XAAQTTEA

  if [[ -n "$1" ]]; then
    export VPN_HOST=$1
  elif [[ -n $(op read "op://TM/TFX VPN/host") ]]; then
    export VPN_HOST=$(op read "op://TM/TFX VPN/host")
  else
    echo "${BIYellow}Please set VPN_HOST env var${Color_Off}"
    return
  fi

  #if [[ -z $VPN_HOST ]]; then
  #  echo "${BIYellow}Please set VPN_HOST env var${Color_Off}"
  #  return
  #fi

  if pgrep -x "openconnect" > /dev/null; then
    echo "${CHECK_MARK}${BICyan}VPN is already running!${Color_Off}"
    return
  else
    echo "${BICyan}Starting the VPN ...${Color_Off}"
    echo "${BLINK}${BIYellow}Approve connection on phone!${Color_Off}"
    # cat ${VPN_CONFIG_PATH}/vpnp | sudo openconnect -bqd --disable-ipv6 --no-dtls --passwd-on-stdin --authgroup=$VPN_GROUP --user=$USER --servercert $VPN_HOST_CERT $VPN_HOST &> /dev/null
    # op read "op://TM/TFX VPN/password" | sudo openconnect -bqd --disable-ipv6 --no-dtls --passwd-on-stdin --authgroup=$(op read "op://TM/TFX VPN/group") --user=$(op read "op://TM/TFX VPN/username") ny4vpn.tfxcorp.com &> /dev/null
    op read "op://TM/TFX VPN/password" | sudo openconnect -bqd --disable-ipv6 --no-dtls --passwd-on-stdin --authgroup=$(op read "op://TM/TFX VPN/group") --user=$(op read "op://TM/TFX VPN/username") --servercert $(op read "op://TM/TFX VPN/cert") $VPN_HOST &> /dev/null
  fi

  if pgrep -x "openconnect" > /dev/null; then
    echo "${REPLACE_2LINE}${CHECK_MARK} VPN started!${Color_Off}"
  else
    echo "${REPLACE_2LINE}${EXCLAMATION_MARK} ${BIRed}VPN failed to start!${Color_Off}"
    # cat ${VPN_CONFIG_PATH}/vpnp | sudo openconnect -bd --disable-ipv6 --no-dtls --passwd-on-stdin --authgroup=$VPN_GROUP --user=$USER --servercert $VPN_HOST_CERT $VPN_HOST
    # op read "op://TM/TFX VPN/password" | sudo openconnect -bd --disable-ipv6 --no-dtls --passwd-on-stdin --authgroup=$(op read "op://TM/TFX VPN/group") --user=$(op read "op://TM/TFX VPN/username") ny4vpn.tfxcorp.com
    op read "op://TM/TFX VPN/password" | sudo openconnect -bd --disable-ipv6 --no-dtls --passwd-on-stdin --authgroup=$(op read "op://TM/TFX VPN/group") --user=$(op read "op://TM/TFX VPN/username") --servercert $(op read "op://TM/TFX VPN/cert") $VPN_HOST
  fi
}

vpn-up "$@"
